const path = require("path");
const { FlatCompat } = require("@eslint/eslintrc");
const js = require("@eslint/js");

const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
});

module.exports = [
  {
    ignores: [
      "test/**",
      "__tests__/**",
      "node_modules/**",
      "vendor/**",
      "public/**",
      "**/coverage/**",
      "*.php",
      "resources/js/libs/font-awesome.5.0.6.js",
    ],
  },
  ...compat.config({
    env: {
      node: true,
      browser: true,
    },
    globals: {
      Vue: "readonly",
      BpmnModdle: "readonly",
      Snap: "readonly",
      Dispatcher: "readonly",
      ProcessMaker: "readonly",
      Processmaker: "readonly",
      _: "readonly",
      $: "readonly",
    },
    extends: ["eslint:recommended", "plugin:vue/recommended", "airbnb-base"],
    parserOptions: {
      parser: "@babel/eslint-parser",
      sourceType: "module",
      ecmaVersion: 2020,
      babelOptions: {
        configFile: path.join(__dirname, "babel.config.json"),
      },
    },
    plugins: ["vue"],
    rules: {
      quotes: ["error", "double"],
      "max-len": ["error", {
        code: 140,
        ignoreComments: true,
      }],
    },
    overrides: [
      {
        files: ["tests/**/*.js"],
        plugins: ["jest"],
        extends: ["plugin:jest/recommended"],
      },
    ],
  }),
  {
    settings: {
      "import/resolver": {
        webpack: {
          config: path.join(__dirname, "webpack.mix.js"),
        },
      },
    },
  },
  {
    files: ["resources/**/*.{js,vue}"],
    languageOptions: {
      globals: {
        moment: "readonly",
        Chart: "readonly",
        VueRouter: "readonly",
      },
    },
    rules: {
      "array-callback-return": "warn",
      "block-scoped-var": "warn",
      camelcase: "warn",
      "class-methods-use-this": "off",
      "comma-dangle": "warn",
      "consistent-return": "warn",
      "default-case": "warn",
      "dot-notation": "warn",
      eqeqeq: "warn",
      "func-names": "off",
      indent: "off",
      "import/export": "warn",
      "import/extensions": "off",
      "import/named": "warn",
      "import/no-duplicates": "warn",
      "import/no-cycle": "off",
      "import/no-extraneous-dependencies": ["warn", {
        devDependencies: [
          "tests/**",
          "**/*.test.js",
          "webpack*.js",
          "webpack-login.mix.js",
        ],
      }],
      "import/no-named-as-default": "warn",
      "import/no-named-as-default-member": "warn",
      "import/no-unresolved": "warn",
      "import/prefer-default-export": "off",
      "lines-between-class-members": "warn",
      "max-len": ["warn", {
        code: 140,
        ignoreComments: true,
      }],
      "no-console": "warn",
      "no-cond-assign": "warn",
      "no-continue": "warn",
      "no-bitwise": "warn",
      "no-case-declarations": "warn",
      "no-empty": "warn",
      "no-eval": "warn",
      "no-extend-native": "warn",
      "no-multi-assign": "warn",
      "no-nested-ternary": "warn",
      "no-prototype-builtins": "warn",
      "no-unreachable": "warn",
      "no-useless-concat": "warn",
      "no-useless-escape": "warn",
      "no-var": "warn",
      "global-require": "warn",
      "guard-for-in": "warn",
      "implicit-arrow-linebreak": "warn",
      "new-cap": "warn",
      "no-await-in-loop": "warn",
      "no-mixed-operators": "warn",
      "no-multiple-empty-lines": "warn",
      "no-new": "warn",
      "no-new-func": "warn",
      "no-param-reassign": "warn",
      "no-plusplus": "warn",
      "no-restricted-globals": "warn",
      "no-restricted-syntax": "warn",
      "no-return-assign": "warn",
      "no-sequences": "warn",
      "no-shadow": "warn",
      "no-trailing-spaces": "warn",
      "no-underscore-dangle": "off",
      "no-unused-expressions": "warn",
      "no-undef": "warn",
      "no-unused-vars": ["warn", {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
      }],
      "no-use-before-define": "warn",
      "no-void": "off",
      "object-shorthand": "warn",
      "prefer-destructuring": "warn",
      "prefer-regex-literals": "warn",
      "prefer-rest-params": "warn",
      "quote-props": "warn",
      quotes: ["warn", "double"],
      radix: "warn",
      "valid-typeof": "warn",
      "vars-on-top": "warn",
      "spaced-comment": "warn",
      "vue/attribute-hyphenation": "off",
      "vue/attributes-order": "off",
      "vue/first-attribute-linebreak": "off",
      "vue/html-indent": "off",
      "vue/html-self-closing": "off",
      "vue/max-attributes-per-line": "off",
      "vue/multi-word-component-names": "off",
      "vue/no-dupe-keys": "warn",
      "vue/no-lone-template": "warn",
      "vue/no-mutating-props": "warn",
      "vue/no-side-effects-in-computed-properties": "warn",
      "vue/no-unused-components": "warn",
      "vue/no-unused-vars": "warn",
      "vue/no-use-v-if-with-v-for": "warn",
      "vue/no-useless-template-attributes": "warn",
      "vue/no-v-html": "warn",
      "vue/require-default-prop": "off",
      "vue/require-prop-type-constructor": "warn",
      "vue/require-prop-types": "off",
      "vue/require-valid-default-prop": "warn",
      "vue/require-v-for-key": "warn",
      "vue/return-in-computed-property": "warn",
      "vue/valid-v-else": "warn",
      "vue/valid-v-for": "warn",
      "eol-last": "warn",
    },
  },
];
