# Global configuration settings for Prometheus
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

# Scrape configurations
scrape_configs:
  # For Prometheus
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          # Replace this with your local processmaker instance
          - processmaker-b.test

