<?php
/**
 * EnvironmentVariablesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ProcessMaker API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@processmaker.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * EnvironmentVariablesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EnvironmentVariablesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createEnvironmentVariables
     *
     * Save a new environment_variables.
     *
     */
    public function testCreateEnvironmentVariables()
    {
    }

    /**
     * Test case for deleteEnvironmentVariables
     *
     * Delete a environment_variables.
     *
     */
    public function testDeleteEnvironmentVariables()
    {
    }

    /**
     * Test case for getEnvironmentVariables
     *
     * Returns all environmentVariables that the user has access to.
     *
     */
    public function testGetEnvironmentVariables()
    {
    }

    /**
     * Test case for getEnvironmentVariablesById
     *
     * Get single environment_variables by ID.
     *
     */
    public function testGetEnvironmentVariablesById()
    {
    }

    /**
     * Test case for updateEnvironmentVariables
     *
     * Update a environment_variables.
     *
     */
    public function testUpdateEnvironmentVariables()
    {
    }
}
