export default [
  {
    type: 'processes',
    name: 'Processes',
    url: '/processes',
    class: 'ProcessMaker\\Models\\Process',
    icon: 'fp-play-outline',
    nameField: 'name',
  },
  {
    type: 'screens',
    name: 'Screens',
    url: '/screens',
    class: 'ProcessMaker\\Models\\Screen',
    icon: 'fp-screen-outline',
    nameField: 'title',
  },
  {
    type: 'scripts',
    name: 'Scripts',
    url: '/scripts',
    class: 'ProcessMaker\\Models\\Script',
    icon: 'fp-script-outline',
    nameField: 'title',
  },
  {
    type: 'data_sources',
    name: 'Data Connectors',
    url: '/data_sources',
    class: 'ProcessMaker\\Packages\\Connectors\\DataSources\\Models\\DataSource',
    icon: 'fp-script-outline',
    nameField: 'name',
  },
  {
    type: 'collections',
    name: 'Collections',
    url: '/saved-searches/collections',
    class: 'ProcessMaker\\Plugins\\Collections\\Models\\Collection',
    icon: 'fp-bpmn-data-store',
    nameField: 'name',
  },
  {
    type: 'decision_tables',
    name: 'Decision Tables',
    url: '/decision_tables',
    class: 'ProcessMaker\\Package\\PackageDecisionEngine\\Models\\DecisionTable',
    icon: 'fp-table',
    nameField: 'name',
  },
  {
    type: 'flow-genies',
    name: 'FlowGenies',
    url: '/designer/flow-genies',
    class: 'ProcessMaker\\Package\\PackageAi\\Models\\FlowGenie',
    icon: 'fp-flowgenie-outline',
    nameField: 'name',
  },
];