export default [
  {
    type: 'process',
    name: 'Processes',
    url: 'api.processes.index',
    class: 'ProcessMaker\\Models\\Process',
    icon: 'fp-play-outline',
    nameField: 'name',
  },
  {
    type: 'screens',
    name: 'Screens',
    url: 'api.screens.index',
    class: 'ProcessMaker\\Models\\Screen',
    icon: 'fp-screen-outline',
    nameField: 'title',
  },
  {
    type: 'scripts',
    name: 'Scripts',
    url: 'api.scripts.index',
    class: 'ProcessMaker\\Models\\Script',
    icon: 'fp-script-outline',
    nameField: 'title',
  },
  {
    type: 'data_sources',
    name: 'Data Connectors',
    url: 'api.data-sources.index',
    class: 'ProcessMaker\\Packages\\Connectors\\DataSources\\Models\\DataSource',
    icon: 'fp-copy',
    nameField: 'name',
  },
  {
    type: 'collections',
    name: 'Collections',
    url: 'saved_searches.collections.index',
    class: 'ProcessMaker\\Plugins\\Collections\\Models\\Collection',
    icon: 'fp-bpmn-data-store',
    nameField: 'name',
  },
  {
    type: 'decision_tables',
    name: 'Decision Tables',
    url: 'api.decision-tables.index',
    class: 'ProcessMaker\\Package\\PackageDecisionEngine\\Models\\DecisionTable',
    icon: 'fp-table',
    nameField: 'title',
  },
  {
    type: 'flow-genies',
    name: 'FlowGenies',
    url: 'flow_genie.index',
    class: 'ProcessMaker\\Package\\PackageAi\\Models\\FlowGenie',
    icon: 'fp-flowgenie-outline',
    nameField: 'name',
  },
];