export default [
  {
    type: 'process',
    name: 'Processes',
    url: 'api.processes.index',
    listingUrl: '/processes',
    class: 'ProcessMaker\\Models\\Process',
    icon: 'fp-play-outline',
    nameField: 'name',
  },
  {
    type: 'pm_block',
    name: 'PM Blocks',
    url: 'api.pm-blocks.index',
    listingUrl: '/designer/pm-blocks',
    class: 'ProcessMaker\\Package\\PackagePmBlocks\\Models\\PmBlock',
    icon: 'fp-pm-block',
    nameField: 'name',
  },
  {
    type: 'screen',
    name: 'Screens',
    url: 'api.screens.index',
    listingUrl: '/designer/screens',
    class: 'ProcessMaker\\Models\\Screen',
    icon: 'fp-screen-outline',
    nameField: 'title',
  },
  {
    type: 'script',
    name: 'Scripts',
    url: 'api.scripts.index',
    listingUrl: '/designer/scripts',
    class: 'ProcessMaker\\Models\\Script',
    icon: 'fp-script-outline',
    nameField: 'title',
  },
  {
    type: 'data_source',
    name: 'Data Connectors',
    url: 'api.data-sources.index',
    listingUrl: '/designer/data-sources',
    class: 'ProcessMaker\\Packages\\Connectors\\DataSources\\Models\\DataSource',
    icon: 'fp-copy',
    nameField: 'name',
  },
  {
    type: 'collection',
    name: 'Collections',
    url: 'saved_searches.collections.index',
    listingUrl: '/collections',
    class: 'ProcessMaker\\Plugins\\Collections\\Models\\Collection',
    icon: 'fp-bpmn-data-store',
    nameField: 'name',
  },
  {
    type: 'decision_table',
    name: 'Decision Tables',
    url: 'api.decision-tables.index',
    listingUrl: '/designer/decision-tables',
    class: 'ProcessMaker\\Package\\PackageDecisionEngine\\Models\\DecisionTable',
    icon: 'fp-table',
    nameField: 'title',
  },
  {
    type: 'flow_genie',
    name: 'FlowGenies',
    url: 'flow_genie.index',
    listingUrl: '/designer/flow-genies',
    class: 'ProcessMaker\\Package\\PackageAi\\Models\\FlowGenie',
    icon: 'fp-flowgenie-outline',
    nameField: 'name',
  },
];
