export const defaultColumns = [
  {
    label: "Request ID",
    field: "id",
    sortable: true,
    default: true,
    width: 115,
    subject: {
      type: "Field",
      value: "id",
    },
  },
  {
    label: "Case #",
    field: "case_number",
    sortable: true,
    default: true,
    width: 95,
    subject: {
      type: "Field",
      value: "case_number",
    },
  },
  {
    label: "Case title",
    field: "case_title",
    sortable: true,
    default: true,
    truncate: true,
    width: 200,
    subject: {
      type: "Field",
      value: "case_title",
    },
  },
  {
    label: "Process",
    field: "name",
    sortable: true,
    default: true,
    width: 200,
    truncate: true,
    subject: {
      type: "Field",
      value: "name",
    },
  },
  {
    label: "Task",
    field: "active_tasks",
    sortable: false,
    default: true,
    width: 200,
    truncate: true,
    subject: {
      type: "Field",
      value: "active_tasks",
    },
  },
  {
    label: "Participants",
    field: "participants",
    sortable: true,
    default: true,
    width: 200,
    truncate: true,
    subject: { type: "ParticipantsFullName" },
    hideSortingButtons: true,
  },
  {
    label: "Status",
    field: "status",
    sortable: true,
    default: true,
    width: 200,
    subject: { type: "Status" },
  },
  {
    label: "Started",
    field: "initiated_at",
    format: "datetime",
    sortable: true,
    default: true,
    width: 200,
    subject: {
      type: "Field",
      value: "initiated_at",
    },
  },
  {
    label: "Completed",
    field: "completed_at",
    format: "datetime",
    sortable: true,
    default: true,
    width: 200,
    subject: {
      type: "Field",
      value: "completed_at",
    },
  },
];
