<?php

namespace ProcessMaker\Services\DataSourceIntegrations\Integrations;

use ProcessMaker\Services\DataSourceIntegrations\Integrations\IntegrationsInterface;

class CrunchbaseService implements IntegrationsInterface
{
    public function getParameters() : array
    {
        // TODO: Implement getParameters() method with real data from Crunchbase
        return [
            'acquirer_identifier',
            'aliases',
            'categories',
            'category_groups',
            'closed_on',
            'company_type',
            'contact_email',
            'created_at',
            'delisted_on',
            'demo_days',
            'description',
            'diversity_spotlights',
            'entity_def_id',
            'equity_funding_total',
            'exited_on',
            'facebook',
            'facet_ids',
            'founded_on',
            'founder_identifiers',
            'funding_stage',
            'funding_total',
            'funds_total',
            'hub_tags',
            'identifier',
            'image_id',
            'image_url',
            'investor_identifiers',
            'investor_stage',
            'investor_type',
            'ipo_status',
            'last_equity_funding_total',
            'last_equity_funding_type',
            'last_funding_at',
            'last_funding_total',
            'last_funding_type',
            'layout_id',
            'legal_name',
            'linkedin',
            'listed_stock_symbol',
            'location_group_identifiers',
            'location_identifiers',
            'name',
            'num_acquisitions',
            'num_alumni',
            'num_articles',
            'num_current_advisor_positions',
            'num_current_positions',
            'num_diversity_spotlight_investments',
            'num_employees_enum',
            'num_enrollments',
            'num_event_appearances',
            'num_exits',
            'num_exits_ipo',
            'num_founder_alumni',
            'num_founders',
            'num_funding_rounds',
            'num_funds',
            'num_investments',
            'num_investors',
            'num_lead_investments',
            'num_lead_investors',
            'num_past_positions',
            'num_portfolio_organizations',
            'num_sub_organizations',
            'operating_status',
            'override_layout_id',
            'owner_identifier',
            'permalink',
            'permalink_aliases',
            'phone_number',
            'program_application_deadline',
            'program_duration',
            'program_type',
            'rank_delta_d30',
            'rank_delta_d7',
            'rank_delta_d90',
            'rank_org',
            'rank_principal',
            'revenue_range',
            'school_method',
            'school_program',
            'school_type',
            'short_description',
            'status',
            'stock_exchange_symbol',
            'stock_symbol',
            'twitter',
            'updated_at',
            'uuid',
            'valuation',
            'valuation_date',
            'website',
            'website_url',
            'went_public_on',
        ];
    }

    public function getCompanies(array $params = []) : array
    {
        // TODO: Implement getCompanies() method with real data from Crunchbase
        return [
            [
                'permalink' => 1,
                'api_path' => '',
                'web_path' => '',
                'name' => 'Amazon',
                'short_description' => 'Amazon is a platform for building process automation solutions.',
                'description' => 'Amazon is a platform for building process automation solutions.',
                'also_known_as' => 'Amazon',
                'profile_image_url' => 'https://processmaker.com/logo.png',
                'primary_role' => 'Company',
                'role_company' => 'Company',
                'role_investor' => 'Investor',
                'role_group' => 'Group',
                'role_school' => 'School',
                'founded_on' => '2010-01-01',
                'founded_on_trust_code' => '2010-01-01',
                'is_closed' => false,
                'closed_on' => '',
                'closed_on_trust_code' => '',
                'num_employees_min' => 100,
                'num_employees_max' => 100,
                'total_funding_usd' => 1000000,
                'stock_exchange' => 'NASDAQ',
                'stock_symbol' => 'AMZN',
                'number_of_investments' => 100,
                'homepage_url' => 'https://www.amazon.com',
                'created_at' => '2021-01-01',
                'updated_at' => '2021-01-01',
                'permalink_aliases' => 'amazon',
                'api_url' => '',
                'investor_type' => 'Venture Capital',
                'contact_email' => 'contact@amazon.com',
                'phone_number' => '+1234567890',
                'rank' => 1,
            ],
            [
                'permalink' => 2,
                'api_path' => '',
                'web_path' => '',
                'name' => 'Telsa',
                'short_description' => 'Telsa is a platform for building process automation solutions.',
                'description' => 'Telsa is a platform for building process automation solutions.',
                'also_known_as' => 'Telsa',
                'profile_image_url' => 'https://google.com/logo.png',
                'primary_role' => 'Company',
                'role_company' => 'Company',
                'role_investor' => 'Investor',
                'role_group' => 'Group',
                'role_school' => 'School',
                'founded_on' => '2010-01-01',
                'founded_on_trust_code' => '2010-01-01',
                'is_closed' => false,
                'closed_on' => '',
                'closed_on_trust_code' => '',
                'num_employees_min' => 100,
                'num_employees_max' => 100,
                'total_funding_usd' => 1000000,
                'stock_exchange' => 'NASDAQ',
                'stock_symbol' => 'AMZN',
                'number_of_investments' => 100,
                'homepage_url' => 'https://www.amazon.com',
                'created_at' => '2021-01-01',
                'updated_at' => '2021-01-01',
                'permalink_aliases' => 'amazon',
                'api_url' => '',
                'investor_type' => 'Venture Capital',
                'contact_email' => 'contact@amazon.com',
                'phone_number' => '+1234567890',
                'rank' => 1,
            ],
        ];
    }

    public function fetchCompanyDetails(string $companyId) : array
    {
        // TODO: Implement fetchCompanyDetails() method with real data from Crunchbase
        return [
            'permalink' => 2,
            'api_path' => '',
            'web_path' => '',
            'name' => 'Telsa',
            'primary_role' => 'Company',
            'short_description' => 'Telsa is a platform for building process automation solutions.',
            'profile_image_url' => 'https://google.com/logo.png',
            'domain' => 'telsa.com',
            'homepage_url' => 'https://www.amazon.com',
            'facebook_url' => 'https://www.facebook.com/telsa',
            'twitter_url' => 'https://www.twitter.com/telsa',
            'linkedin_url' => 'https://www.linkedin.com/telsa',
            'city_name' => 'San Francisco',
            'region_name' => 'California',
            'country_code' => 'US',
            'created_at' => '2021-01-01',
            'updated_at' => '2021-01-01',
            'api_url' => '',
            'stock_exchange' => 'NASDAQ',
            'stock_symbol' => 'AMZN',
        ];
    }
}
