{
 "title": "ProcessMaker Dashboard",
 "description": "Different metrics from ProcessMaker",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Screen Cache Hit/Miss Rates",
   "type": "bargauge",
   "description": "Visual representation of cache performance showing the hit and miss rates for screens.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(processmaker_cache_hits_total{cache_key=~\"pid_.*\"})",
     "legendFormat": "Hits"
    },
    {
     "expr": "max(processmaker_cache_misses_total{cache_key=~\"pid_.*\"})",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Settings Cache Hit/Miss Rates",
   "type": "bargauge",
   "description": "Visual representation of cache performance showing the hit and miss rates for settings.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(processmaker_cache_hits_total{cache_key=~\"setting_.*\"})",
     "legendFormat": "Hits"
    },
    {
     "expr": "max(processmaker_cache_misses_total{cache_key=~\"setting_.*\"})",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Screen Cache Sizes",
   "type": "gauge",
   "description": "Visual representation of cache performance showing the hit and miss rates for screens.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(5, processmaker_cache_memory_bytes{label=~\"screen.*\"})",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Tasks Completed",
   "type": "barchart",
   "description": "Visual representation of cache performance showing the hit and miss rates for screens.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(processmaker_activity_completed_total)",
     "legendFormat": "Tasks completed"
    }
   ]
  }
 ]
}