const ICONS = {
  User: "fa-user",
  Group: "fa-users",
  Screen: "fa-file-alt",
  ScreenCategory: "fa-file-alt",
  Script: "fa-code",
  ScriptCategory: "fa-code",
  Process: "fa-play-circle",
  SubProcess: "fa-play-circle",
  ProcessCategory: "fa-play-circle",
  Category: "",
  EnvironmentVariable: "fa-lock",
  Signal: "bpmn-icon-end-event-signal",
  DataConnector: "fa-cog",
  DataSource: "fa-cog",
  Collection: "fa-database",
  Vocabulary: "fa-book",
  CommentConfiguration: "fa-comments",
  SavedSearch: "fa-table",
  SavedSearchChart: "fa-chart-line",
  SavedSearchOption: "",
  SavedSearchReport: "fa-clock",
  Media: "fa-photo-video",
  Embed: "fa-link",
  Launchpad: "fa-rocket",
};

export default {
  ICONS,
};
