const icons = [
  "Default Icon",
  "3 Star Hotel",
  "24",
  "Add",
  "Alarm",
  "Apple Fruit",
  "Audio Wave",
  "Autumn",
  "Bank Building",
  "Bank Cards",
  "Banknotes",
  "Basketball",
  "Binoculars",
  "Blueprint",
  "Bookmark",
  "Box",
  "Boy On The Rocket",
  "Broom",
  "Bug",
  "Business Report",
  "Cafe",
  "Cameras",
  "Cancel",
  "Car Sale",
  "Cash and Credit Card",
  "Cash Receipt",
  "Certification",
  "Checked Checkbox",
  "Cheesecake",
  "Cheque",
  "Circled Play",
  "Circled User Female Skin Type 7",
  "Circled User Male Skin Type 7",
  "Classroom",
  "Clipboard",
  "Clock",
  "Cloud Sync",
  "Code",
  "Coins",
  "Coming Soon",
  "Coworking",
  "Create Order",
  "Crowd",
  "Cute Cake",
  "CV",
  "Cycling",
  "Discount",
  "Doctor Female Skin Type 2",
  "Doctors Bag",
  "Emergency Exit",
  "Enter",
  "Error",
  "Exam",
  "Exclamation Mark",
  "Factory",
  "Fantasy",
  "File",
  "Filing Cabinet",
  "Flip Chart",
  "Flower",
  "Folder",
  "Food",
  "Form",
  "Gear",
  "Genie",
  "Gift",
  "Goal",
  "Graduate",
  "Graduation Cap",
  "Group",
  "Group Of Companies",
  "Hammer",
  "Heart with Pulse",
  "Helicopter",
  "Help",
  "Historical",
  "Home",
  "Hospital",
  "Hotel Bed",
  "Increase",
  "Ingredients",
  "Integrated Circuit",
  "In Transit",
  "Key",
  "Knight",
  "Laptop",
  "Leave",
  "Letter",
  "Logout",
  "Magic Trick",
  "Messaging",
  "Money Box",
  "Mortgage",
  "Motorcycle Delivery Single Box",
  "Multiple Devices",
  "Music",
  "Office",
  "Office-1",
  "Ok",
  "Online Maintenance Portal",
  "Online Support",
  "Open End Wrench",
  "Pass Fail",
  "Password",
  "Pawn",
  "Permanent Job",
  "Phone",
  "Phone Message",
  "Pill",
  "Ping",
  "Pizza",
  "Plane",
  "Print",
  "Protect",
  "Puzzles",
  "Queen",
  "Radiator",
  "Realtime",
  "Receipt Approved",
  "Sandwich",
  "Season Sale",
  "Security Guard",
  "Sedan",
  "Sent",
  "Shop",
  "Shopping Cart",
  "Smartphone",
  "Soccer Ball",
  "Sport",
  "Student Center",
  "Summer",
  "Tax",
  "Tea",
  "Teacher",
  "Tear-Off Calendar",
  "Test Account",
  "Test Passed",
  "Ticket Purchase",
  "Traveler",
  "U Turn to Left",
  "U Turn to Right",
  "Vial Virus",
  "Virus",
  "Virus Free",
  "Walking Skin Type 2",
  "Wallet",
  "Warning Shield",
  "Web Advertising",
  "Winter",
  "Wizard",
  "Workstation",
  "Worldwide Delivery",
];

export default class {
  static list() {
    const list = [];
    icons.forEach((icon) => {
      list.push({
        label: icon,
        value: icon,
      });
    });
    return list;
  }
}
