import Vue from "vue";
import MonacoEditor from "vue-monaco";
import debounce from "lodash/debounce";
import VueFormRenderer from "@processmaker/screen-builder";
import DataSummary from "./components/DataSummary";
import RequestDetail from "./components/RequestDetail";
import AvatarImage from "../components/AvatarImage";
import RequestErrors from "./components/RequestErrors";
import Timeline from "../components/Timeline";
import TimelineItem from "../components/TimelineItem";
import RequestScreens from "../requests/components/RequestScreens";

Vue.component("DataSummary", DataSummary);
Vue.component("RequestDetail", RequestDetail);
Vue.component("AvatarImage", AvatarImage);
Vue.component("RequestErrors", RequestErrors);
Vue.component("MonacoEditor", MonacoEditor);
Vue.component("Timeline", Timeline);
Vue.component("TimelineItem", TimelineItem);
Vue.component("RequestScreens", RequestScreens);
Vue.use("vue-form-renderer", VueFormRenderer);
window.debounce = debounce;
