name: Translate Changed Lines

on:
  push:
    paths:
      - 'resources/lang/en.json'

jobs:
  translate_and_create_pr:
    name: Translate and create PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Translate changed lines to Spanish
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORG: ${{ secrets.OPENAI_ORG }}
        run: python .github/workflows/scripts/translate.py es
        
      - name: Translate changed lines to French
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORG: ${{ secrets.OPENAI_ORG }}
        run: python .github/workflows/scripts/translate.py fr
        
      - name: Translate changed lines to German
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORG: ${{ secrets.OPENAI_ORG }}
        run: python .github/workflows/scripts/translate.py de

      - name: Create PR for updated translated files
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update translations for changed lines'
          title: 'Update translations for changed lines'
          body: 'This PR updates translations for the changed lines in en.json for Spanish, French, and German.'
          branch: 'translate/changed-lines'
          labels: 'translation, automated'

      - name: Check if PR was created
        if: steps.create_pr.outputs.pull-request-number == ''
        run: echo "No changes to translations, no PR created."
